apiVersion: apps/v1
kind: Deployment
metadata:
  name: telco-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telco
  template:
    metadata:
      labels:
        app: telco
    spec:
      containers:
      - name: telco-app
        image: telco-app:v2
        ports:
        - containerPort: 3000
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MESSAGE
