apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telco-ingress
spec:
  rules:
  - host: telco.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: telco-app-service
            port:
              number: 3000
